db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
    ports: 
        - 3316:3306
web:
    image: test01:5.6.23-apache
    volumes:
        - /Users/knt9mac/Docker/test/web:/var/www/html
    links:
        - db:mysql
    ports:
        - 8080:80
